<?php
\TAO::App()->SetTitle('Дисконтная программа | «СМ-Стоматология»');
\TAO::App()->SetPageProperty("description", "Дисконтная программа «СМ-Стоматология». Записаться на прием к стоматологу или задать вопрос он-лайн"); 
?>

<h1 class="b-heading">
	Дисконтная программа
	<a href="#" class="b-heading__link hidden-md-down"
		data-toggle="modal" data-target="#modal-ask-question"
	>
		Есть вопросы?
	</a>
</h1>
