<?php
\TAO::App()->SetTitle('Безопасность пациента | «СМ-Стоматология»');
\TAO::App()->SetPageProperty("description", "Безопасность пациента «СМ-Стоматология». Записаться на прием к стоматологу или задать вопрос он-лайн"); 
?>

<h1 class="b-heading">
	Безопасность пациента
	<a href="#" class="b-heading__link hidden-md-down"
		data-toggle="modal" data-target="#modal-ask-question"
	>
		Есть вопросы?
	</a>
</h1>

