<?php
\TAO::App()->SetTitle('Программа годового обслуживания | «СМ-Стоматология»');
\TAO::App()->SetPageProperty("description", "Программа годового обслуживания «СМ-Стоматология». Записаться на прием к стоматологу или задать вопрос он-лайн"); 
?>
<h1 class="b-heading">
	Программа годового обслуживания
	<a href="#" class="b-heading__link hidden-md-down"
		data-toggle="modal" data-target="#modal-ask-question"
	>
		Есть вопросы?
	</a>
</h1>

