<div class="b-aside-form">
	<hr>
	<div class="b-form b-form--inline">
		<form action="">
			<div class="b-form__group">
				<div class="b-form__select b-custom-select b-custom-select--style-2">
					<select name="" class="form-control b-form__control"
					        data-theme="select-theme-style2">
						<option value="1">Укажите симптом</option>
						<option value="2">симптом 1</option>
						<option value="3">симптом 2</option>
						<option value="4">симптом 3</option>
						<option value="5">симптом 4</option>
					</select>
				</div>
			</div>

			или

			<div class="b-form__group">
				<div class="b-form__select b-custom-select b-custom-select--style-2">
					<select name="" class="form-control b-form__control"
					        data-theme="select-theme-style2">
						<option value="1">Укажите болезнь</option>
						<option value="2">болезнь 1</option>
						<option value="3">болезнь 2</option>
						<option value="4">болезнь 3</option>
						<option value="5">болезнь 4</option>
					</select>
				</div>
			</div>

		</form>
	</div>
</div>
