<?php
$infoblockArray = (array)$this->infoblock;
$priceId = $infoblockArray["\0*\0currentProperties"]["prices"]["ID"];
foreach ($this->propertiesData[$priceId] as $priceItem) {
	$priceIdList[] = $priceItem["VALUE"];
}

$priceList = [];
$index = 0;
foreach ($priceIdList as $priceId) {
	$price = \TAO::infoblock('prices')->getItems([
		'filter' => [
			'ID' => $priceId,
			'ACTIVE' => 'Y'
		]
	]);
	if(!empty($price)) {
		addItemToArray($priceList,  $price[0], $index);
	}
}
function addItemToArray(&$array ,$item, $index)
{
	if($array[$index]) {
		addItemToArray($array,$item, $index + 1);
	} else {
		$array[$index] = $item;
	}
}

ksort($priceList);
?>
<?php
global $APPLICATION;
$APPLICATION->IncludeComponent("sm:text", "", ['IBLOCK_ID' => 23,'ELEMENT_ID' => 	15723], false);
?>

<table class="table b-table">
	<thead>
	<tr>
		<th>Наименование услуги</th>
		<th>Цена&nbsp;(руб.)&nbsp;*</th>
	</tr>
	</thead>
	<tbody>
	<?php foreach ($priceList as $price) {?>
		<tr>
			<td><?= $price->title() ?></td>
			<td><?= $price['sum'] ?> руб.</td>
		</tr>
		<script type="application/ld+json">
		{
			"@context": "http://schema.org",
			"@type": "Offer",
			"availability": "http://schema.org/InStock",
			"itemOffered": "Service",
			"name": "<?= $price->title() ?>",
			"url": "<?= $_SERVER['HTTP_REFERER'] ?>",
			"priceCurrency": "RUB"
		}
		</script>
	<?php } ?>
	</tbody>
</table>
<p>
	Принимаем к оплате банковские карты VISA, MASTERCARD, MAESTRO
	<?/*<img src="<?= TAO::frontendUrl('/img/common/payment-methods.png') ?>" alt=""
	     style="vertical-align: middle; margin-left: 10px;">*/?>
</p>

