<?php
$isActicveStock = true;
if ($this->dateTo() > time()) {
    $routeSection = ['url' => '/stock/', 'title' => 'Акции'];
}
else {
    $routeSection = ['url' => '/stock/archive/', 'title' => 'Архив акций'];
    $isActicveStock = false;
}
\TAO::navigation()->route()->addArray([
    $routeSection,
    ['url' => $this->url(), 'title' => $this->title()]
]);
$this->preparePage();
\TAO::app()->setTitle($this->title() . ' | "СМ-Стоматология"');
?>
<div class="b-heading">
    <h1><?=$this->title()?></h1>
    <a href="#" class="b-heading__link hidden-md-down"
       data-toggle="modal" data-target="#modal-ask-question"
    >
        Есть вопросы?
    </a>
</div>


<div class="b-sale b-sale--card">
    <div class="row">
        <div class="col-sm-3 b-sale__left">
            <a href="#">
                <img class="b-sale__img"
                     src="<?=$this->previewPicture()->resizedImage('fit212x138')?>">
            </a>
        </div>
        <div class="col-sm-9 b-sale__right">

            <div class="b-sale__date">
                <? if ($this->property("PERIOD")->value()): ?>
                    <?=$this->property("PERIOD")->value()?>
                <? else: ?>
                    <?php
                    $monthFrom = ToLower(GetMessage("MONTH_" . intval($this->dateFrom('m')) . "_S"));
                    $monthTo = ToLower(GetMessage("MONTH_" . intval($this->dateTo('m')) . "_S"));
                    ?>

                    <?=$this->dateFrom('d') . ' ' . $monthFrom . ' ' . $this->dateFrom('Y')?>
                    &ndash;
                    <?=$this->dateTo('d') . ' ' . $monthTo . ' ' . $this->dateTo('Y')?>
                <? endif; ?>
            </div>

            <div class="b-sale__text">
                <?=$this['PREVIEW_TEXT']?>
            </div>
        </div>
    </div>

    <div class="b-sale__content">
        <?=$this['DETAIL_TEXT']?>
    </div>

    <?php
    //global $USER;
    //if ($USER->IsAdmin()):
    if ($this['show_form']->value() == '42b7da9f7fe310d0339f17ea4bbcd80b'):
        ?>
        <hr class="hr--light">
        <div class="b-form b-form--inline b-form--bg" style="background: #e1e1e1;">
            <h3 class="b-heading--secondary b-heading--black"><?=$this['title_form']->value();?></h3>

            <div class="stock-form">
                <div class="accept-message ok-message" style="display: none">Спасибо за обращение. Ваша заявка принята.
                    Наш специалист свяжется с Вами в ближайшее время
                </div>
                <form method="post" action="" class="tao-form">
                    <div class="row">
                        <div class="col-md-6 col-lg-4">
                            <div class="b-form__group b-form__group--float-label">
                                <input class="form-control b-form__control b-field-name form-name" name="name"
                                       type="text">
                                <label for="">Имя</label>
                            </div>
                        </div>

                        <div class="col-md-6 col-lg-4">
                            <div class="b-form__group b-form__group--float-label b-form__group--required">
                                <input class="form-control b-form__control b-field-phone b-form__phone form-phone"
                                       name="phone" type="text">
                                <label for="">Телефон<span class="required">*</span></label>
                            </div>
                        </div>
                        <?php if (!empty($this['time_form']->value())): ?>
                        <div class="col-md-6 col-lg-4">
                            <div class="b-form__group">
                                <div class="b-form__select b-custom-select b-custom-select--style-2">
                                    <select name="time" class="form-control b-form__control form-time">
                                        <option value="" selected="selected" disabled="disabled">Желаемое время</option>
                                        <?php foreach ($this['time_form']->value() as $value): ?>
                                            <option value="<?=$value;?>"><?=$value;?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <?php endif; ?>
                        <div class="col-md-12 col-lg-4">
                            <div class="b-form__group b-form__buttons">
                                <input name="taoform" value="stock_form" type="hidden">
                                <input class="btn btn-primary btn-lg btn-submit" value="Отправить заявку" type="submit">
                                <div class="agreement" style="text-align: left;">Нажимая на кнопку, вы даете
                                    согласие<br> на <a rel="canonical" href="/about/obrabotka-dannykh/" target="_blank">обработку
                                        своих персональных данных</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="b-form__group b-form__note">
                        Запись через сайт является предварительной. Наш сотрудник свяжется с вами в ближайшее время для
                        подтверждения записи на прием.
                    </div>
                </form>
            </div>
        </div>

    <? //= $this['email_form']->value();
    ?>
    <?=$this['text_form']->value()['TEXT'];?>
        <script>
            (function ($) {
                $(document).ready(function () {
                    var send_stock_form = true;
                    $('.stock-form form').submit(function () {
                        $(".stock-form input").removeClass("b-form__control--error");
                        var go = true;
                        var name = $('.stock-form .form-name').val();
                        var phone = $('.stock-form .form-phone').val();
                        <?php if(!empty($this['time_form']->value())): ?>
                        var time = $('.stock-form .form-time').val();
                        <?php else: ?>
                        var time = '';
                        <?php endif; ?>

                        if (phone == '') {
                            $(".stock-form .form-phone").addClass("b-form__control--error").focus();
                            go = false;
                        }

                        if (go && send_stock_form) {
                            $('.stock-form input[type="submit"]').prop('disabled', true);
                            send_stock_form = false;
                            $('.stock-form .btn-submit input').hide();
                            $('.stock-form .btn-submit .progress').show();
                            $.ajax({
                                url: "/include/forms/offers_static_ajax.php",
                                type: "POST",
                                data: {name: name, phone: phone, time: time, id: <?= $this->id(); ?>},
                                dataType: "html",
                                success: function (jsondata) {
                                    $(".stock-form form").hide();
                                    $(".stock-form .accept-message").show();
                                },
                            });
                        }
                        return false;
                    });
                });
            }(jQuery));
        </script>

    <?php endif; ?>
    <?php //endif; ?>

    <div class="b-shale__share">
        <script src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
        <script src="//yastatic.net/share2/share.js"></script>
        <div class="ya-share2"
             data-services="collections,vkontakte,facebook,odnoklassniki,moimir,twitter"
             data-counter=""></div>
    </div>

    <div class="b-sale__pager">
        <?php if ($this->next($isActicveStock)) { ?>
            <a href="<?=$this->next($isActicveStock)->url()?>" class="b-sale__link-next">
                Следующая
                <br>
                акция
            </a>
        <?php } ?>
        <?php if ($this->prev($isActicveStock)) { ?>
            <a href="<?=$this->prev($isActicveStock)->url()?>" class="b-sale__link-prev">
                Предыдущая
                <br>
                акция
            </a>
        <?php } ?>
    </div>

    <?php if ($this->dateTo() > time()) { ?>
        <p class="b-heading--secondary b-heading--black">
            Записаться по акции
        </p>

        <?=\TAO::Form('Appointment')->setOption('layout', 'appointment-in-text')->render()?>
    <?php } ?>
</div>
