<?php
$text = explode('<!-- {form} -->', $item['PREVIEW_TEXT']);
print $text[0];
if(isset($text[1])) {
	print \TAO::Form('Callback')->setOption('layout','callback-in-text')->render();
	print $text[1];
}
?>

<hr>
<?php /*блок с выпадающим текстом*/?>
<?php if($item['dropdown']->value()) { ?>
	<div class="b-content-dd">
		<div class="b-content-dd__links b-content-dd__links--block b-content-dd__items">
			<?php $i = 1; ?>
			<?php foreach ($item['dropdown']->valueData() as $ddText) {?>
				<div>
					<a href="#bb<?= $i ?>"
					   class="b-content-dd-link">
						<span class="b-content-dd-link__txt"><?= $ddText['DESCRIPTION']?></span>
					</a>
					<div class="b-content-dd-item" id="bb<?= $i ?>">
						<?/* <h3><?= $ddText['DESCRIPTION']?></h3> */?>
						<?= $ddText['VALUE']['TEXT']?>
					</div>
				</div>
				<?php $i++ ?>
			<?php } ?>
		</div>

	</div>

	<hr>
<?php } ?>

<?php /*слайдер*/ ?>
<?php if($item['sliders']->value()) { ?>
	<h2>
		<?= $item['title_slider'] ?>
	</h2>

	<div class="b-content-slider owl-carousel">
		<?php foreach ((array)$item['sliders']->valueData() as $slide) { ?>
			<div class="b-content-slider__item">
				<div class="b-content-slider__item-title">
					<?= $slide['DESCRIPTION'] ?>
				</div>
				<?= $slide['VALUE']['TEXT'] ?>
			</div>
		<?php } ?>
	</div>

	<hr>
<?php } ?>

<?php
$text = explode('<!-- {form} -->', $item['DETAIL_TEXT']);
print $text[0];
if(isset($text[1])) {
	print \TAO::Form('Callback')->setOption('layout','callback-in-text')->render();
	print $text[1];
}
?>
<!--<br>

<hr class="hr--light"> -->

<blockquote class="blockquote blockquote--dark text-xs-left">
	Узнать подробности и записаться на консультацию специалиста вы можете по телефону:
	<b>+7 (495) 777-48-06</b>, а так же заполнив форму:
</blockquote>

<!--<p class="b-heading--secondary b-heading--black">
	Записаться на прием
</p>-->

<?//= \TAO::Form('Appointment')->setOption('layout','appointment-in-text')->render() ?>

