<?php
$doctorID = $item['doctors']->value();
?>
<div class="m-doctors">
	<div class="container">
		<h2 class="page-title-3">Наши врачи</h2>
		<?php require \TAO::infoblock('doctors')->viewPath('search-form.phtml'); ?>
		<?php require \TAO::infoblock('doctors')->viewPath('filter-list.phtml'); ?>
	</div>
</div>

<?= \TAO::Form('Callback')->setOption('layout','callback-in-text')->render(); ?>

<?php if(stripos($_SERVER["REDIRECT_URL"], 'services/protezirovanie-ortopediya')) { ?>
	<div class="feedback-form">
		<div class="container">
			<?= \TAO::Form('Appointment')->setOption('layout','appointment-in-text')->render() ?>
		</div>
	</div>
<?php } ?>
