<?php
if($item['technologies']->value()) {
	$technologies = \TAO::infoblock('technologies')->getItems([
		'filter' => ['ACTIVE', 'ID' => $item['technologies']->value()]
	]);
}
?>

<div class="m-equipment">
	<div class="container">
		<h2 class="m-equipment__main-title">Оборудование</h2>

		<div class="m-equipment__wrap">
		<div class="m-equipment__items">
			<?php $i = 0;?>
			<?php  foreach($technologies as $technology){ ?>
				<?php $i++; ?>
				<a class="m-equipment__item" href="<?= $technology->url() ?>">
					<div class="m-equipment__card">
						<div class="m-equipment__image"><img src="<?= $technology->previewPicture()->resizedImage(fit480x306) ?>"></div>
						<div class="m-equipment__desc">
							<div class="m-equipment__title"><?= $technology->title() ?></div>
							<div class="m-equipment__brand">
								<?php if(!empty($technology->property('country')->value())) {
									echo $technology->property('country')->value();
								}?>
								<?php if(!empty($technology->property('country')->value()) && !empty($technology->property('brand')->value())) {
									echo '/';
								}?>
								<?php if(!empty($technology->property('brand')->value())) {
									echo $technology->property('brand')->value();
								}?>
								<br>
								<?= $technology['PREVIEW_TEXT']?>
							</div>
						</div>
					</div>
				</a>
			<?php } ?>
		</div>
	</div>
	</div>
</div>
